# in this setup, the controller also acts as slurm db daemon for simplicity

# SLURM database daemon-specific
slurm_mariadb_host: 192.168.121.14
slurm_mariadb_user: slurmdbd
slurm_mariadb_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34356431343834383630316466323032616433663832363563336261623062333735626236383938
          3436643233626234636131303835616163653166656164650a336462373566353665636234373261
          64396238633932343663663233383638326133393136623664303466326138653135653061383763
          3265383566643332390a663738646338323661336433313065383763396636363935313832306331
          33363264373763653234393534643565623433613636393165333530363135343234
slurm_mariadb_dbname: slurm_acct_db
