munge_key_b64: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36363366353736663064653534333564666330316232396537383235626566306330343437346162
          3365623034666561653030623632663932353566343664650a636162323133656230373734633035
          61653332383435363436383439376138303631313531643763366364636664643436323562373466
          6333313533336634300a363465336364633233623064346361383365643965363738376136633333
          32343762336364303332623461366364353138386363373332366533303830346431373963306636
          31636438353038626231353261636364393662616132343831653663343730376236656261313836
          37313534633739333436643062646638306131303262373833396266353365623436353033623466
          64626536336336333062346439313961636238626663333131303338646533633836353036323730
          35363732663133373264303339396230306335393430313961613434373965613632383031326339
          61383234623463336134363834313964623335623434316261333531336466613464306435336664
          30306633626536613935326462623933313166396633343761666661386263303763633662653566
          33383735306533646635386633356363366639353364623461646166336633376163376636316534
          30386662663264393362363532383431303761613662303066653863636536656130366236376265
          61366534346630656139383738643835376231646161383662646238633565613430643265323439
          65326264353739666366363934653531646163346461303439646531646631313562303266363933
          37613033653336306331666635313462333561303936383366663533656132343566386336623032
          31653661303465653539666437636666376630366331386230633065386161303261636261303330
          62646161313339663230383864323239323532313732643761363834653935666464613733383236
          37313966353663353662633539336538613939323466626537306337373037336330376263306539
          32306438306165646332323863616634643666393563643866393861376561663032623731383431
          35646234343731316361613437666534376462313133306566323339313966643738306133636364
          35393337656637313364373165623735626635393233656465663235313733306462363130353566
          32373638396164643964363962313461303431383566313735663333636434666236656633613835
          61623934616337306431333336656565393437333537633038343239373130373961636666313336
          37633433363139376562636632356332303362323665396639326464653365373132373831383335
          63613537616163383665366466663966363064616334623366346139663032666366376164366334
          34363331333837623133646238303535306663613463306632636138353739646331316663343662
          64653264323464643263376632383664333761393431613634663334333035326565343866643934
          31663834343434306232393737353434393031373066633433623834383966326331646631396532
          39326637376363643335616264346163366233386436613637363836636364313430626437326466
          66623532393532383038306432343739356265386265613431396463643764336463643338353565
          37393164613262303162633761633765636330343339656534386562326437636363633631363665
          32303339623835326461363034393363343330646663626464376536383561313366326331326534
          38333166366264356364666332393036313539333162393066303263396631636630626464353032
          64386666363736373832653934376565393031653566333832363866306437633862616238393131
          62623163393534363338323961313765636661326265376366636161633265316161373434336539
          66633865303836656634303965306630333031303965343162383432373533323561343363393331
          37303133643538666430643763323062653166616266333137636262623565653164343963333236
          35353235656461336564313237333138326439666664333461363230376136376339383937306663
          34663263333165313563646433663039353432313631393036613635653636313836353930376465
          37356235613165663766316336643338656261653338376638396261356561343438663230643562
          36393430333063393730363536613730356565393537356534663832313963366562353835323131
          32643566613539626432323362323461363432636239663937376130383364356333366362313934
          37303763363161636631383565346266633866393963643239376439613536386436653435623738
          36383562663332316364666234313835643130636136633936356462623630653739643736633030
          33353661633162336263616465653439353638653333613263373136326333613833623765633431
          66333430323839613736386461653036303963653965613961366262376564323564653531666636
          32336333386663383762303230373030633366366534653136383432353932616465643661336430
          37333465626166353434336563383139613932353834653537643934373730623563393932633432
          36323964653139633331326136643334643161353363313637353265663036376565396433663765
          33663665633331613665383234323138323461666135376135393531386135366135623834336264
          32313438306564343462393435656661656339643337356161376462396266616630386438623230
          38346430343835653934376132353761663162653034623430313530646433366636653062363662
          65666331323335646139333265333731383130633833323763373032646266656163376430373463
          34313639313535663533633636393965656366306532346135343838373939396263366230626161
          33666531323661366665373737383433633636323763373830393531393864326366653938333563
          63663737633636613662613063626533366132326462653136356466613131326663636338383730
          35313738386266386534633438363466336564366337633335613661326634306463363238636333
          65663862393236363530386132663238376533626231363730656533376630646535326136643439
          35333233376564363236346161626631336534626365623764653864386236303563383839383565
          38323634633030333932383936626439353465613863303738343034393734346234663364303036
          30666133326162393066323337326532633139343063393732356231313738373363323662393661
          65623966303562383631623037666237613935616536393432613038303635623332653866333235
          61303033343838393331646637313132383262643162366564373065363163333933316132633561
          33346266656530336531326238333138643735356631626138313231393336663865346336646136
          62613166396435646134303133383862303163643566613432383062663762376566346238623564
          61383233393237353666396531626135636261383466356266626238353364396364633937383130
          65616564356135623161303032656135366264633966373833333062326437666133636665383532
          66346335353734333965393437653236393337623861666336333231363032653233333331333461
          38393139663430306638353630346131663138303464303766636462396566316462646430373062
          31346566393663653830653335663638323930393536323662393965356564306463373137656137
          33353538643164373734666462336438373436343535303032313533613637356164356164316136
          31646166396261336139333263656334363634313839386236623766343961346535
