# Distribute key 

---
- name: Decode MUNGE key
  ansible.builtin.set_fact:
    munge_key: "{{ munge_key_b64 | ansible.builtin.b64decode }}"

- name: Distribute MUNGE Key to All Nodes
  copy:
    content: "{{ munge_key }}"
    dest: /etc/munge/munge.key
    owner: "{{ munge_svc_user }}"
    group: "{{ munge_svc_group }}"
    mode: '0400'
  notify: Restart Munge
